name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential dh-make debhelper
      
    - name: Build package
      run: |
        cd path/to/your/source
        debuild -us -uc
