name: Build and Export .deb Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Użyj odpowiedniej wersji Pythona

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-stdeb fakeroot debhelper

      - name: Build the .deb package
        run: |
          pip install stdeb
          python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: dist/deb_dist/*.deb
